import React from "react";
const Home = () => {
    return (React.createElement("div", { className: "home-container" },
        React.createElement("section", { className: "hero" },
            React.createElement("div", { className: "hero-content" },
                React.createElement("h1", { className: "hero-title" }, "Welcome to MindMotion"),
                React.createElement("p", { className: "hero-description" }, "Your journey to a calm and centered mind begins here"),
                React.createElement("button", { className: "cta-btn" }, "Get Started"))),
        React.createElement("section", { className: "benefits" },
            React.createElement("h2", null, "Why Choose MindMotion?"),
            React.createElement("div", { className: "benefit-items" },
                React.createElement("div", { className: "benefit-item" },
                    React.createElement("h3", null, "Inspiring Quotes"),
                    React.createElement("p", null, "Find daily doses of wisdom and motivation to center your mind.")),
                React.createElement("div", { className: "benefit-item" },
                    React.createElement("h3", null, "Soothing Soundscapes"),
                    React.createElement("p", null, "Immerse yourself in calming melodies and ambient sounds for deep relaxation.")),
                React.createElement("div", { className: "benefit-item" },
                    React.createElement("h3", null, "Mood Insights & Tracking"),
                    React.createElement("p", null, "Track your mood, get personalized insights, and stay motivated with expert guidance.")))),
        React.createElement("section", { className: "testimonials" },
            React.createElement("h2", null, "What Our Users Say About MindMotion"),
            React.createElement("div", { className: "testimonial-item" },
                React.createElement("p", null, "\"MindMotion helps me start my day with peace and inspiration. The quotes are perfect!\""),
                React.createElement("h4", null, "- Jane Doe")),
            React.createElement("div", { className: "testimonial-item" },
                React.createElement("p", null, "\"The soundscapes are incredibly calming, and I love discovering new quotes. A wonderful app!\""),
                React.createElement("h4", null, "- David K.")),
            React.createElement("div", { className: "testimonial-item" },
                React.createElement("p", null, "\"I never knew how much I needed this app until I started using it. It has transformed my daily routine.\""),
                React.createElement("h4", null, "- Sarah L."))),
        React.createElement("section", { className: "cta" },
            React.createElement("h2", null, "Ready to Find Your Inner Peace?"),
            React.createElement("button", { className: "cta-btn" }, "Explore MindMotion Now"))));
};
export default Home;
